# Generated by Django 4.2 on 2023-04-29 05:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Level",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("level", models.CharField(max_length=200, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_delete", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "Level",
            },
        ),
        migrations.CreateModel(
            name="Technology",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("technology_name", models.CharField(max_length=200, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_delete", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "Technology",
            },
        ),
    ]
