# Generated by Django 4.2 on 2023-05-04 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("quesapp", "0002_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="McqQuestions",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("mcq_ques", models.CharField(max_length=255)),
                ("option1", models.CharField(max_length=255)),
                ("option2", models.CharField(max_length=255)),
                ("option3", models.CharField(max_length=255)),
                ("option4", models.CharField(max_length=255)),
                ("answer", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("is_delete", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "level",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="quesapp.level",
                    ),
                ),
                (
                    "technology",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quesapp.technology",
                    ),
                ),
            ],
            options={
                "db_table": "McqQuestions",
            },
        ),
    ]
