# Generated by Django 4.2 on 2023-05-04 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("quesapp", "0003_mcqquestions"),
    ]

    operations = [
        migrations.CreateModel(
            name="TechnicalQuestion",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("tech_ques", models.CharField(max_length=255)),
                ("keywords", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("is_delete", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "level",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="quesapp.level",
                    ),
                ),
                (
                    "technology",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quesapp.technology",
                    ),
                ),
            ],
            options={
                "db_table": "TechnicalQuestion",
            },
        ),
    ]
