# Generated by Django 4.2 on 2023-05-06 09:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quesapp", "0004_technicalquestion"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Technology",
            new_name="TechnologyList",
        ),
        migrations.AlterModelTable(
            name="technologylist",
            table="TechnologyList",
        ),
    ]
