# Generated by Django 3.2.18 on 2023-04-24 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_role_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role_id',
            field=models.ForeignKey(default='User', on_delete=django.db.models.deletion.CASCADE, to='users.role'),
        ),
    ]
