# Generated by Django 3.2.18 on 2023-04-20 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skilltest', '0001_initial'),
        ('sessiontest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionquestion',
            name='question_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='skilltest.questions'),
        ),
    ]
