# Generated by Django 3.2.18 on 2023-04-24 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessiontest', '0002_alter_sessionquestion_question_1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SessionQuestion',
        ),
    ]
