# Generated by Django 4.2 on 2023-05-08 06:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_alter_userprofile_technology_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="technology_name",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(default=["General"], max_length=200),
                size=None,
            ),
        ),
    ]
