# Generated by Django 3.2.18 on 2023-04-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_logs_role_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='interest',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
