# Generated by Django 4.2 on 2023-05-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_userprofile_profile_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="preferred_tech",
            field=models.CharField(default="None", max_length=200),
        ),
    ]
