# Generated by Django 4.2 on 2023-05-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_userprofile_preferred_tech"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="preferred_tech",
            field=models.CharField(default="General", max_length=200),
        ),
    ]
