# Generated by Django 4.2 on 2023-05-08 05:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_alter_userprofile_preferred_tech"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="preferred_tech",
            new_name="technology_name",
        ),
    ]
