# Generated by Django 3.2.18 on 2023-04-19 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='TestSessionInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'TestSessionInfo',
            },
        ),
        migrations.CreateModel(
            name='TestSessionItems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_video_path', models.FileField(upload_to='videos/TestSessionItems/user_directory_path')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skilltest.questions')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skilltest.testsessioninfo')),
            ],
            options={
                'db_table': 'TestSessionItems',
            },
        ),
        migrations.CreateModel(
            name='QAnswer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('keywords', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skilltest.questions')),
            ],
            options={
                'db_table': 'QAnswer',
            },
        ),
    ]
