# Generated by Django 3.2.18 on 2023-04-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilltest', '0006_alter_testsessionitems_user_video_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsessionitems',
            name='user_video_path',
            field=models.FileField(upload_to='videos/TestSessionItems/user_directory_path'),
        ),
    ]
