# Generated by Django 3.2.18 on 2023-04-24 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skilltest', '0008_alter_testsessionitems_user_video_path'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
        migrations.AlterModelTable(
            name='question',
            table='Question',
        ),
    ]
